# Generated by Django 2.0.6 on 2019-02-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_auto_20190212_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=10, verbose_name='作者'),
        ),
    ]
