# Generated by Django 2.1.7 on 2019-02-20 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_auto_20190213_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='正文'),
        ),
    ]
