# Generated by Django 2.1.7 on 2019-02-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0016_auto_20190220_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_number', models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读数')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_number',
        ),
        migrations.AddField(
            model_name='readnum',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lib.Article'),
        ),
    ]
