# Generated by Django 2.1.7 on 2019-02-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0017_auto_20190220_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='article',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
