# Generated by Django 2.0.6 on 2019-03-09 16:28

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0019_auto_20190221_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=DjangoUeditor.models.UEditorField(verbose_name='正文'),
        ),
    ]
