# Generated by Django 2.1.7 on 2019-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='read_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
