name: myblog
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: dreamcoin1998/myblog@master
      run: docker build -t myblog